### ISSUE TITLE
Optimize write requests with master

### ISSUE THREAD

**Issue by shihuili1218** [shihuili1218/klein#8]
**Is your feature request related to a problem? Please describe.**
In order to reduce the probability of livelocks and improve negotiation efficiency, write requests need to be restricted to the master, but this needs to be configured by the user through parameters

**Describe the solution you'd like**
1. In `PaxosConsensus#proposeAsync`, judge whether the write request can only be executed by the master
2. It is implemented by proxy. The corresponding proxy objects are initialized according to the parameter configuration, such as MasterProxy and ProposerProxy.
3. If only the master can handle the write request, other members will forward the request to the master when they receive it

**Describe alternatives you've considered**

**Additional context**

**Comment by WeiBiCheng** [comment]
https://github.com/shihuili1218/klein/pull/13

**Comment by shihuili1218** [comment]
https://github.com/shihuili1218/klein/pull/32
